[package]
name = "huobi-chain"
version = "0.0.1-rc.1"
authors = ["Muta Dev <muta@nervos.org>"]
edition = "2018"

[dependencies]
muta = { git = "https://github.com/nervosnetwork/muta", tag = "v0.0.1-rc.1-huobi" }
protocol = { git = "https://github.com/nervosnetwork/muta", tag = "v0.0.1-rc.1-huobi", package = "muta-protocol" }

tokio = { version = "0.2", features = ["macros", "rt-core"]}
derive_more = "0.15"
runtime = "0.3.0-alpha.7"
runtime-tokio = "0.3.0-alpha.6"
clap = "2.33"

metadata = { path = "services/metadata" }
asset = { path = "services/asset" }
riscv = { path = "services/riscv" }
node_manager = { path = "services/node_manager" }

[workspace]
members = [
  "services/metadata",
  "services/riscv",
  "services/asset",
  "services/node_manager"
]
